### ISSUE TITLE
Enquiry about status of this project

### ISSUE THREAD

**Issue by matanster** [probprog/anglican#3]
Not an issue but a question ― is this now practically speaking an abandoned project, or is it just perfect enough so that no further development has been necessary since 2016 within the implemented feature set? I wonder what folks here think...

Would you otherwise recommend any specific Java library for the time being, along the lines of Scala's [Figaro](https://github.com/p2t2/figaro)? I think https://github.com/amidst/toolbox looks nice in terms of its accounting for concurrency, but it looks kind of newish too.

**Comment by dtolpin** [comment]
This project is actively being developed. However, the project repository is at bitbucket (https://bitbucket.org/probprog/anglican) and we synchronize this repository occasionally for visibility. I need it to set up a script to keep these repositories in sync but didn't get around to do this until now. Will do.

**Comment by matanster** [comment]
Oh, thanks!! and glad I asked as I'd not ever guess that!

**Comment by LSaldyt** [comment]
It would actually be nice if the git repo said something about this, since git is so standard these days. Does the github repository ever get pulled back into the bitbucket one?

**Comment by dtolpin** [comment]
why don't you ask the committers. i too would love to see a new release
